openapi: '3.0.3'
info:
  title: PersonalInfoApi
  version: '1.0'

paths:
  /AddUser:
    post:
      responses:
        '200':
          description: OK
  /DeleteUser:
    delete:
      description: ''
      parameters: [
          ]
      responses:
        '200':
          description: OK
  /GetUser:
    get:
      description: ''
      parameters: []
      responses:
        '200':
          description: OK
  /ChangeUser:
    put:
      description: ''
      parameters: []
      responses:
        '200':
          description: OK
  
